#! /bin/sh
# /etc/init.d/flask_daemon

#
### BEGIN INIT INFO
# Provides:          autoC_daemon
# Processname:       autoConfig
# Required-Start:     
# Required-Stop:     
# Default-Start:     S 2 
# Default-Stop:      0 1 6
# Short-Description: Router initial auto configuration 
# Description:       Flask is an open source, A micro python web framework.
#                    http://flask.com
### END INIT INFO

exec 1>/tmp/autoC_daemon.log 2>&1


case "$1" in
  start)
    echo "Starting Heart Beat Daemon"
    # run application you want to start
    python3 /www/web/_autoConfig/autoConfig.py &
    ;;
  stop)
    echo "Stopping HeartBead Daemon"
    # kill application you want to stop
    kill $(ps aux | grep "python3 /www/web/_autoConfig/autoConfig.py" | grep -v grep | awk '{print $2}') 
    ;;
  restart)
    echo "Restarting the HeartBeat Daemon"
    kill $(ps aux | grep "python3 /www/web/_autoConfig/autoConfig.py" | grep -v grep | awk '{print $2}') &
    python3 /www/web/_autoConfig/autoConfig.py &
    ;;
  *)
    echo "Usage: /etc/init.d/autoC_daemon{start|stop|restart}"
    exit 1
    ;;
esac

exit 0
