#! /bin/sh
# /etc/init.d/logs_daemon

#
### BEGIN INIT INFO
# Provides:          logs_daemon
# Processname:       logs_daemon
# Required-Start:    $network $autoConfig
# Required-Stop:     $network
# Default-Start:     S 4 
# Default-Stop:      0 1 6
# Short-Description: Flask , Router web interface 
# Description:       Flask is an open source, A micro python web framework.
#                    http://flask.com
### END INIT INFO
#exec 1>/tmp/logs_daemon.log 2>&1

case "$1" in
  start)
    echo "Starting Logs Daemon...  "
    # run application you want to start
    python3 /www/web/_include/log_reset.py &
    #return 0
    ;;
  stop)
    echo "Stopping flask_daemon"
    # kill application you want to stop
    kill $(ps aux | grep "python3 /www/web/_include/log_reset.py" | grep -v grep | awk '{print $2}')
    ;;
  *)
    echo "Usage: /etc/init.d/logs_daemon  {start|stop}"
    exit 1
    ;;
esac

exit 0
